name: cookie-ci

on:
  push:
    branches:
      - "master"

jobs:
  test-frontend:
    runs-on: ubuntu:latest
    steps: 
      - name: Check out repository
        uses: actions/checkout@v3
      - name: test frontend
        run: go test
        working-directory: frontend

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: build frontend
        run: docker build . -t frontend
        working-directory: frontend

  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: build backend
        run: docker build -t backend
        working-directory: backend
